export const projects = [
  {
    id: 1,
    title: "Positivus landing page",
    description:
      "A landing page for a music festival, showcasing event details, lineup, and ticket information.",
    image: "./assets/images/positivus.png",
    category: "landing",
    technologies: ["HTML", "Tailwind CSS", "Lenis", "GSAP"],
    links: {
      github: "https://github.com/khaledsaoud15/landing-page",
      live: "https://positivus-tau-eight.vercel.app/",
    },
    fullDescription:
      "This project is a landing page for the Positivus music festival, designed to provide visitors with essential information about the event. The page features a visually appealing layout that highlights the festival's lineup, schedule, and ticketing options. Built using HTML and Tailwind CSS, the design is responsive and user-friendly. The integration of Lenis ensures smooth scrolling throughout the page, while GSAP adds engaging animations to enhance the user experience. Overall, this landing page effectively captures the essence of the Positivus festival and encourages visitors to attend.",
  },
  {
    id: 2,
    title: "Plane Multipurpose Platform",
    description:
      "A multipurpose platform for Seo, Websites, and Business consulting, providing a seamless travel planning experience.",
    fullDescription:
      "Plane is a multipurpose platform designed to cater to various needs, including SEO services, website development, and business consulting. The platform offers a seamless travel planning experience, allowing users to easily navigate through different services and find the solutions they need. With a user-friendly interface and comprehensive features, Plane aims to simplify the process of managing online presence and business growth. Whether you're looking for expert SEO strategies, custom website design, or professional business advice, Plane provides a one-stop solution for all your needs.",
    category: "saas",
    technologies: ["React", "Tailwind CSS", "Node.js", "Express"],
    links: {
      github: "",
      live: "https://singular-bombolone-02cb5e.netlify.app/",
    },
    image: "./assets/images/plane.png",
  },
];

export const skills = [
  {
    id: 1,
    name: "HTML",
    icon: "./assets/icons/html.svg",
    color: "#E34F26",
    background: "#F06529",
  },
  {
    id: 2,
    name: "CSS",
    icon: "./assets/icons/css.svg",
    color: "#1572B6",
    background: "#2965F1",
  },
  {
    id: 3,
    name: "JavaScript",
    icon: "./assets/icons/javascript.svg",
    color: "#F7DF1E",
    background: "#F7DF1E",
  },
  {
    id: 4,
    name: "Tailwind CSS",
    icon: "./assets/icons/tailwindcss.svg",
    color: "#38B2AC",
    background: "#38B2AC",
  },
  {
    id: 5,
    name: "React",
    icon: "./assets/icons/react.svg",
    color: "#61DAFB",
    background: "#61DAFB",
  },
  {
    id: 6,
    name: "Node.js",
    icon: "./assets/icons/nodejs.svg",
    color: "#339933",
    background: "#339933",
  },
  {
    id: 7,
    name: "Express",
    icon: "./assets/icons/express.svg",
    color: "#000000",
    background: "#000000",
  },
  {
    id: 8,
    name: "MongoDB",
    icon: "./assets/icons/mongodb.svg",
    color: "#47A248",
    background: "#47A248",
  },
  {
    id: 9,
    name: "Git",
    icon: "./assets/icons/git.svg",
    color: "#F05032",
    background: "#F05032",
  },
  {
    id: 10,
    name: "GitHub",
    icon: "./assets/icons/github.svg",
    color: "#181717",
    background: "#181717",
  },
  {
    id: 11,
    name: "GSAP",
    icon: "./assets/icons/gsap.svg",
    color: "#88CE02",
    background: "#88CE02",
  },
  {
    id: 12,
    name: "Lenis",
    icon: "./assets/icons/lenis.svg",
    color: "#000000",
    background: "#000000",
  },
  {
    id: 13,
    name: "Figma",
    icon: "./assets/icons/figma.svg",
    color: "#F24E1E",
    background: "#F24E1E",
  },
  {
    id: 14,
    name: "Prisma",
    icon: "./assets/icons/prisma.svg",
    color: "#fea745",
    background: "#ff74ac",
  },
  {
    id: 15,
    name: "Vercel",
    icon: "./assets/icons/vercel.svg",
    color: "#000000",
    background: "#000000",
  },
  {
    id: 16,
    name: "Netlify",
    icon: "./assets/icons/netlify.svg",
    color: "#00C7B7",
    background: "#00C7B7",
  },
  {
    id: 17,
    name: "Postman",
    icon: "./assets/icons/postman.svg",
    color: "#FF6C37",
    background: "#FF6C37",
  },
  {
    id: 18,
    name: "Docker",
    icon: "./assets/icons/docker.svg",
    color: "#2496ED",
    background: "#2496ED",
  },
  {
    id: 19,
    name: "SQL",
    icon: "./assets/icons/sql.svg",
    color: "#326CE5",
    background: "#326CE5",
  },
  {
    id: 20,
    name: "My SQL",
    icon: "./assets/icons/mysql.svg",
    color: "#4479A1",
    background: "#4479A1",
  },
  {
    id: 21,
    name: "postgreSQL",
    icon: "./assets/icons/postgresql.svg",
    color: "#336791",
    background: "#336791",
  },
];
